; App configuration

; db configuration
[db]
sms       = mysql://root:admin@localhost/sms
migrate   = false
pool_size = 10
smsgw     = mysql://root:admin@localhost/smsgw

; smtp address and credentials
[smtp]
server = 192.168.91.10
sender = AVISO DTCA <admred.vpor@etecsa.cu>
login  = admred.vpor@etecsa.cu:Marzo.2025*
tls    = false
ssl    = false

[api_sms]
enviar   = http://10.30.12.8/api/sms/enviar.php
